// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/// @title IAgentVaultStylus
/// @notice Exact ABI of the deployed Stylus (Rust/WASM) vault, generated by `cargo run --features export-abi`.
/// @dev Regenerate after any change to vigiles-vault/src/lib.rs. Do not hand-edit.
interface IAgentVaultStylus {
    function depositErc20(address token, uint256 amount) external;

    function withdrawErc20(address token, uint256 amount) external;

    function createSessionKey(address agent, uint256 expiry, address[] memory tokens, uint256[] memory per_trade_caps, uint256[] memory daily_caps, address[] memory adapters) external;

    function revokeSessionKey(address agent) external;

    function setPriceFeed(address token, address feed) external;

    function setSequencerFeed(address feed) external;

    function setSessionSlippage(address agent, uint256 max_slippage_bps) external;

    function setSessionGuards(address agent, uint256 window_start, uint256 window_end, uint256 weekday_mask, uint256 max_trades_per_hour, uint256 heartbeat_interval) external;

    function heartbeat(address agent) external;

    function setPositionCap(address agent, address token, uint256 max_position) external;

    function executeTrade(address user, address token_in, address token_out, uint256 amount_in, uint256 min_amount_out, address adapter, bytes32 intent_hash, bytes calldata data) external returns (uint256);

    function getBalance(address user, address token) external view returns (uint256);

    function getSession(address user, address agent) external view returns (bool, uint256, uint256);

    function getTokenPolicy(address user, address agent, address token) external view returns (bool, uint256, uint256, uint256);

    function isAdapterAllowed(address user, address agent, address adapter) external view returns (bool);

    function getSessionGuards(address user, address agent) external view returns (uint256, uint256, uint256, uint256, uint256, uint256, uint256, uint256, uint256);

    function canTradeNow(address user, address agent) external view returns (bool);

    function getPositionCap(address user, address agent, address token) external view returns (uint256);

    function getOracleConfig(address user, address agent, address token) external view returns (address, address, uint256);

    error SessionKeyInactive();

    error SessionKeyExpired();

    error SpendLimitExceeded();

    error DailyLimitExceeded();

    error TokenNotAllowed();

    error AdapterNotAllowed();

    error InsufficientBalance();

    error ZeroAddress();

    error ZeroAmount();

    error ReentrancyError();

    error SafeMathError();

    error ExternalCallFailed();

    error OverSpent();

    error InsufficientOutput();

    error InvalidCap();

    error InvalidAdapter();

    error InvalidToken();

    error OutsideTradingWindow();

    error VelocityLimitExceeded();

    error HeartbeatMissed();

    error PositionCapExceeded();

    error MissingIntent();

    error InvalidGuard();

    error StalePriceFeed();

    error SequencerDown();

    error GracePeriodNotOver();

    error SlippageExceeded();
}
